/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 67e0b5fb32867cfa0ee496d19e1e3e03)
interface __BaseEnv_CloudflareEnv {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	PUBLIC_ORIGIN: string;
	ENVIRONMENT: string;
	ANGLE_API_ORIGIN: string;
	ANGLE_BACKEND: Fetcher /* angle-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "ENVIRONMENT" | "ANGLE_API_ORIGIN">> {}
}
