/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerEnv worker/bindings.d.ts` (hash: 39f636705b2c863ac27f1864bb2fff6b)
interface __BaseEnv_WorkerEnv {
	ASSETS: Fetcher;
	PUBLIC_ORIGIN: string;
	ENVIRONMENT: string;
	ANGLE_API_ORIGIN: string;
	ANGLE_BACKEND: Fetcher /* angle-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "ENVIRONMENT" | "ANGLE_API_ORIGIN">> {}
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}