// Worker entry. OpenNext serves every request; the cron pre-renders social images into R2
// so link previews are served from storage instead of waiting for a render.
// @ts-ignore Generated by `opennextjs-cloudflare build`.
import handler from '../.open-next/worker.js';
import { categoriesFor, categorySlug, readCatalog, type Env } from './catalog';

// A render takes about 3 s of CPU; a few per run stay well within the CPU limit.
const RENDERS_PER_RUN = 4;
// Recent stories are the ones being shared; older cards still render on first request.
const EPISODES_PER_RUN = 50;

export default {
  fetch: handler.fetch,
  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    // Local previews read the public API, as lib/server/catalog.ts does.
    const episodes = await readCatalog(env.ENVIRONMENT === 'local' ? { ...env, ANGLE_BACKEND: undefined } : env);
    const categories = ['new', 'popular', ...categoriesFor(episodes).map(categorySlug)];
    const paths = ['/api/og-image', ...categories.map(slug => `/api/og-image/category/${slug}`), ...episodes.slice(0, EPISODES_PER_RUN).map(episode => `/api/og-image/${episode.id}`)];
    let rendered = 0;
    for (const path of paths) {
      const response: Response = await handler.fetch(new Request(new URL(path, env.PUBLIC_ORIGIN)), env, ctx);
      // Read rather than cancel: cancelling Next's streamed response fails the cron run.
      await response.arrayBuffer();
      if (response.headers.get('X-Social-Image') === 'rendered' && ++rendered >= RENDERS_PER_RUN) break;
    }
  },
};
